### PR TITLE
added readline support

### PR DESCRIPTION
**Pull request by A-UNDERSCORE-D**
This adds readline support, meaning that among other things, your lines don't get cut up if you're typing and a new raw line comes in, arrow keys can be used to edit lines, and history is kept

### CODE REVIEW

**Comment by DanielOaks** [comment]
Awesome, nice change. So I'm gonna do some work on top of this and ensure that we preserve Windows compat, maybe make this functionality configurable, and will definitely merge it in!

**Comment by jesopo** [comment]
bump xoxox

**Comment by slingamn** [comment]
https://github.com/chzyer/readline looks abandoned. `rlwrap(1)` has been working OK for me, e.g.:

`rlwrap ircdog --tls testnet.ergo.chat 6697`

**Comment by DanielOaks** [comment]
I think the main trouble I was having with this pr was just keeping windows+ansi compatibility is hard – if there's a solution/lib/etc that can provide this functionality while keeping those (at the same time, ie ansi on windows) working then I'm happy!

**Comment by slingamn** [comment]
I took another look at this using `github.com/chzyer/readline v1.5.1`. I'm having some weird issues with the library. `defer rl.Close()` gets stuck here:

https://github.com/chzyer/readline/blob/7f93d88cd5ffa0e805d58d2f9fc3191be15ec668/terminal.go#L228

until the user presses the enter key. This stops the app from exiting in response to a server-side disconnection (e.g. one caused by the `QUIT` command).

I could try putting together a minimal test case for this and showing it to upstream...

**Comment by slingamn** [comment]
Not calling `rl.Close()` is not a viable workaround: if it isn't called, (for example, if `os.Exit()` or `log.Fatalf` terminates the program), it leaves the terminal in a broken state.

**Comment by slingamn** [comment]
https://github.com/chzyer/readline/issues/217

**Comment by A-UNDERSCORE-D** [comment]
Was generally behaving when I created this pr, however I haven't touched this in quite a while

**Comment by slingamn** [comment]
Sorry, I got lazy and was using this as the tracking issue for readline. I opened a real tracking issue at #28

**Pull request closed without merging**
